# Generated by Django 3.2 on 2021-04-27 04:50

from django.db import migrations, models
import mainprofileapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprofileapp', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service')),
                ('service_description', models.CharField(max_length=500, verbose_name='Description')),
                ('service_image', models.ImageField(default='service_pic/default.png', upload_to=mainprofileapp.models.image_path)),
            ],
        ),
    ]
