# Generated by Django 3.2 on 2021-04-27 16:53

from django.db import migrations, models
import django.utils.timezone
import mainprofileapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprofileapp', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Event Name')),
                ('participants', models.CharField(max_length=200, verbose_name='Participants')),
                ('event_description', models.TextField(verbose_name='Description')),
                ('event_image', models.ImageField(default='event_pic/default.png', upload_to=mainprofileapp.models.image_path_event)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
